apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  projectID: akuity-nicholas-morey
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane
      name: gcp-secret
      key: creds