apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: 'gke-autopilot'
    namespace: crossplane-system
  source:
    repoURL: 'https://charts.crossplane.io/stable'
    targetRevision: 1.11.3
    chart: crossplane
    helm:
      parameters:
        # Fix conflict with GKE autopilot settings resource quotas.
        - name: resourcesCrossplane.limits.cpu
          value: 'null'
        - name: resourcesCrossplane.limits.memory
          value: 'null'
        - name: resourcesCrossplane.requests.cpu
          value: 'null'
        - name: resourcesCrossplane.requests.memory
          value: 'null'
        - name: resourcesRBACManager.limits.cpu
          value: 'null'
        - name: resourcesRBACManager.limits.memory
          value: 'null'
        - name: resourcesRBACManager.requests.cpu
          value: 'null'
        - name: resourcesRBACManager.requests.memory
          value: 'null'
        - name: xfn.resources.limits.cpu
          value: 'null'
        - name: xfn.resources.limits.memory
          value: 'null'
        - name: xfn.resources.requests.cpu
          value: 'null'
        - name: xfn.resources.requests.memory
          value: 'null'
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
