apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: 'gke-autopilot'
    namespace: crossplane-system
  source:
    repoURL: 'https://charts.crossplane.io/stable'
    targetRevision: 1.11.3
    chart: crossplane
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/containers[]/resources
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
